using JetBrains.Annotations;
using Microsoft.Extensions.AI;

namespace AIObservabilityAndEvaluationWorkshop.Definitions.Lessons;

[UsedImplicitly]
[Lesson(1, 7, "MEAI Observability", needsInput: true,
    informationalScreenTitle: "MEAI Observability",
    informationalScreenMessage: "This lesson demonstrates OpenTelemetry observability for AI interactions. After you send a message, check the Aspire Dashboard to see traces, logs, and metrics generated by the AI call.",
    informationalScreenSupportsMarkdown: false,
    inputPromptTitle: "MEAI Observability - Message Input",
    inputPromptMessage: "Enter a message to send to the AI (observability data will be captured):")]
public class MEAIObservabilityLesson(IChatClient chatClient) : LessonBase
{
    protected override async Task<string> RunAsync(string message)
    {
        ChatResponse response = await chatClient.GetResponseAsync(message);
        return response.ToString();
    }
}
